author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
title: seguros
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1495555865112692
  brandStrength: 0.1336410769727081
  lightness: 0.4885393294971436
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  rhythmicContrast: 0.5460043968632817
typography_spectrum: 0.7264041954185814
layout_spectrum: 0.08319919114001095
name: ADRIANO JACOMETO
