typography_spectrum: 0.22192744840867817
color:
  saturation: 0.1324383111204952
  brandStrength: 0.33417177898809314
  lightness: 0.10073224105872214
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
  rhythmicContrast: 0.7591914492659271
layout_spectrum: 0.23449523467570543
author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
name: ADRIANO JACOMETO
navigation:
  - name: >-
      Seguro Pirata - Clube de Benefícios ,Associações e Cooperativas - ISSO É
      SEGURO?
    id: 0a8f0934-4e2e-4584-80ea-4cbe198bb719
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: seguros
