layout_spectrum: 0.2815818276721984
typography_spectrum: 0.7788757686503232
color:
  saturation: 0.39496355690062046
  brandStrength: 0.09687493112869561
  lightness: 0.6504450310021639
  brandColors:
    - '#189AD5'
    - '#0D2C53'
    - '#0000FF'
    - '#00FFFF'
    - '#0D6995'
  rhythmicContrast: 0.2806342141702771
author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
name: ADRIANO JACOMETO
navigation:
  - name: >-
      Seguro Pirata - Clube de Benefícios ,Associações e Cooperativas - ISSO É
      SEGURO?
    id: 0a8f0934-4e2e-4584-80ea-4cbe198bb719
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: seguros
