typography_spectrum: 0.858986887615174
content_rating:
  adult: true
color:
  brandStrength: 0.5956344020087272
  lightness: 0.3880802746862173
  saturation: 0.18826007819734514
  rhythmicContrast: 0.21246150974184275
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
opengraph:
  type: 'https://www.facebook.com/FanpageJACOMETOSEGUROS'
layout_spectrum: 0.7902311258949339
author:
  name: Adriano Jacometo
  email: adriano@jacometo.com.br
  url: www.jacometoseguros.com.br
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f6698267-8962-4b6e-acdb-038bf3c310c4.png
name: ADRIANO JACOMETO
title: seguros
