typography_spectrum: 0.7264041954185814
color:
  saturation: 0.7781114680692554
  brandStrength: 0.9600997250527143
  lightness: 0.7715894894208759
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  rhythmicContrast: 0.4758779045660049
layout_spectrum: 0.23449523467570543
author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
name: ADRIANO JACOMETO
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: seguros
