author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
title: seguros
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6135068635921925
  brandStrength: 0.5322659320663661
  lightness: 0.5976427653804421
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  rhythmicContrast: 0.47698613558895886
typography_spectrum: 0.009077672148123384
layout_spectrum: 0.41207923158071935
name: ADRIANO JACOMETO
