author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
title: seguros
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6854300764389336
  brandStrength: 0.6432952233590186
  lightness: 0.48467151587828994
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.3425696617923677
typography_spectrum: 0.5297614790033549
layout_spectrum: 0.6075656425673515
name: ADRIANO JACOMETO
