author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
title: seguros
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1882601
  brandStrength: 0.5956344020087272
  lightness: 0.547261
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  rhythmicContrast: 0.2124615
typography_spectrum: 0.4914071
layout_spectrum: 0.9274973
name: ADRIANO JACOMETO
