author:
  name: Adriano Jacometo
  email: adriano@jacometo.combr
title: seguros
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6820588014088571
  brandStrength: 0.3051493791863322
  lightness: 0.9898851762991399
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  rhythmicContrast: 0.6809239010326564
typography_spectrum: 0.8025067078415304
layout_spectrum: 0.9274973
name: ADRIANO JACOMETO
